### ISSUE TITLE
请求的脚本已被删除

### ISSUE THREAD

**Issue by oblessnoob** [Azure99/osu-download-booster#2]
https://greasyfork.org/zh-CN/scripts/395607-osu-download-booster

**Comment by cdwcgt** [comment]
我感觉删除的原因可能是这个commit
0639418203e08dbaf7ddd102b754e1f5819f39cf
为什么这个东西要加一个Google Analytics

**Comment by Azure99** [comment]
已重新上传并添加tracking标注，增加谷歌统计的原因是为了分析用户使用情况，以便于合理调整CDN降低成本

**Comment by oblessnoob** [comment]
https://greasyfork.org/zh-CN/scripts/429781-osu-download-booster
